## Dct coeffiecient of the sequence##

In [8]:
#Discreate Cosine Transform
#Created By- Mayur Raul
#enrollment Number- BT17ECE067

import numpy as np
import scipy.fftpack as sft
F=np.arange(16)*1.0
F=np.reshape(F,(-1,4))

#Original Matrix:
F

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [9]:

F=np.reshape(F,(-1,2))

F 


array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.],
       [10., 11.],
       [12., 13.],
       [14., 15.]])

In [10]:
Y=sft.dct(F,axis=1,norm='ortho')
Y 

array([[ 0.70710678, -0.70710678],
       [ 3.53553391, -0.70710678],
       [ 6.36396103, -0.70710678],
       [ 9.19238816, -0.70710678],
       [12.02081528, -0.70710678],
       [14.8492424 , -0.70710678],
       [17.67766953, -0.70710678],
       [20.50609665, -0.70710678]])

In [12]:
Mr=np.array([1,0])
Y=np.dot(Y,np.diag(Mr))
Y 


array([[ 0.70710678,  0.        ],
       [ 3.53553391,  0.        ],
       [ 6.36396103,  0.        ],
       [ 9.19238816,  0.        ],
       [12.02081528,  0.        ],
       [14.8492424 ,  0.        ],
       [17.67766953,  0.        ],
       [20.50609665,  0.        ]])

In [13]:
Y=np.reshape(Y,(-1,4)) 
Y

array([[ 0.70710678,  0.        ,  3.53553391,  0.        ],
       [ 6.36396103,  0.        ,  9.19238816,  0.        ],
       [12.02081528,  0.        , 14.8492424 ,  0.        ],
       [17.67766953,  0.        , 20.50609665,  0.        ]])

In [14]:
Y=Y.T
Y=np.reshape(Y,(-1,2))
Y=sft.dct(Y,axis=1,norm='ortho')
Mc=np.array([1,0])
Y=np.dot(Y,np.diag(Mc))
Y=np.reshape(Y,(-1,4))
Y=Y.T
Y

array([[ 5.,  0.,  9.,  0.],
       [ 0.,  0.,  0.,  0.],
       [21.,  0., 25.,  0.],
       [ 0.,  0.,  0.,  0.]])