# ZIG ZAK Compression##

In [3]:
#ZIG ZAK Compression
#Created By- Mayur Raul
#enrollment Number- BT17ECE067

import numpy as np

image = np.array([[1,2,6,7], [3,5,8,13], [4,9,12,14], [10,11,15,16]])
print(image)

print("shape = ",np.shape(image))
[rows,columns]=np.shape(image) 

[[ 1  2  6  7]
 [ 3  5  8 13]
 [ 4  9 12 14]
 [10 11 15 16]]
shape =  (4, 4)


In [4]:
zig_zak=[]

solution=[[] for i in range(rows+columns-1)] 
for i in range(rows): 
    for j in range(columns): 
        sum=i+j 
        if(sum%2 ==0): 
   
            solution[sum].insert(0,image[i][j]) 
        else: 
  
            solution[sum].append(image[i][j]) 
          
for i in solution: 
    for j in i: 
        print(j,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 