In [1]:
import numpy as np
import math

# Input Image Matrix - 3x3 Matrix
image_matrix = np.array([[1,3,5], [4,4,3], [5,2,2]])
print('Image Matrix is :')
print(image_matrix)

length = list(image_matrix.shape)[0]
height = list(image_matrix.shape)[1]

# Gray Level Matrix
gray_level  = np.array([0,1,2,3,4,5,6,7])

# Counting Number of Pixels for each Gray Level
no_of_pixels = np.array([0,0,0,0,0,0,0,0])

for i in range(8):
    no_of_pixels[i] = (image_matrix == i).sum()

print('\nGray Levels   : ',gray_level)
print('No. of Pixels : ',no_of_pixels)


# Computing Smax, Smin, rmax, rmin
# Smax = Maximum pixel value in histogram stretched image
# Smin = Minimum pixel value in histogram stretched image
# rmax = Maximum gray level value in original image
# rmin = Minmum gray level value in original image

Smax = max(gray_level)
Smin = min(gray_level)

# Computing rmax
rmax = 0
for j in range(Smax, 0, -1):
    if (no_of_pixels[j] != 0):
        rmax = j
        break

# Computing rmin        
rmin = 0
for k in range(0, Smax + 1, 1):
    if (no_of_pixels[k] != 0):
        rmin = k
        break

# Printing Smax, Smin, rmax, rmin
print('\nSmax = ',Smax,', Smin = ',Smin)
print('rmax = ',rmax,', rmin = ',rmin)

# Computing Histogram Stretched Matrix 
S = 0
histogram_strected_mat = []
for l in range(Smax + 1):
    if ((gray_level[l] >= rmin) and (gray_level[l] <= rmax)):
        r = gray_level[l]
        S = int(round(((Smax - Smin)/(rmax - rmin))*(r - rmin) + Smin))
        histogram_strected_mat.append(S)
    elif (gray_level[l] < rmin):
        S = Smin
        histogram_strected_mat.append(S)
    else:
        S = Smax
        histogram_strected_mat.append(S)

# Printing Histogram Stretched Matrix       
print('\nHistogram Stretched Matrix : ',histogram_strected_mat)


# Output Image Matrix - 3x3 Matrix

0# Computing Output Image Matrix
output_image_matrix = np.array([[0,0,0], [0,0,0], [0,0,0]])
for m in range(length ):
    for n in range(height):
        a = image_matrix[m, n]
        b = list(gray_level).index(a)
        output_image_matrix[m, n] = histogram_strected_mat[b]

# Printing Output Image Matrix    
print('\nOutput Image Matix is :\n',output_image_matrix)

Image Matrix is :
[[1 3 5]
 [4 4 3]
 [5 2 2]]

Gray Levels   :  [0 1 2 3 4 5 6 7]
No. of Pixels :  [0 1 2 2 2 2 0 0]

Smax =  7 , Smin =  0
rmax =  5 , rmin =  1

Histogram Stretched Matrix :  [0, 0, 2, 4, 5, 7, 7, 7]

Output Image Matix is :
 [[0 4 7]
 [5 5 4]
 [7 2 2]]


In [2]:

# Input Image Matrix - 3x3 Matrix
image_matrix = np.array([[1,3,5], [4,4,3], [5,2,2]])
print('Image Matrix is :')
print(image_matrix)

# Output Image Matrix - 3x3 Matrix
print('\nOutput Image Matix is :\n',output_image_matrix)

Image Matrix is :
[[1 3 5]
 [4 4 3]
 [5 2 2]]

Output Image Matix is :
 [[0 4 7]
 [5 5 4]
 [7 2 2]]
